In [2]:
import numpy as np
import numpy.linalg as npl
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import sympy
from sympy import *
from IPython.core.interactiveshell import InteractiveShell
from mpl_toolkits.mplot3d import Axes3D
from sklearn.datasets import make_blobs
from sklearn.neighbors import KernelDensity
import itertools as it
import seaborn as sns
import scipy
from scipy import stats
from scipy.stats import gaussian_kde
from scipy.stats import multivariate_normal
from matplotlib.gridspec import GridSpec
from matplotlib import cm
import math
from scipy.integrate import trapz
import os
import torch
from tqdm import tqdm
import numpy as np
import random
from datetime import datetime
import time
from omegaconf import OmegaConf
from torchvision import transforms
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torch.optim import AdamW
from torch.optim import lr_scheduler
import pandas as pd
import torchvision
from set import HistoDataset
from torch import nn
import torch
from kornia.color import lab_to_rgb, rgb_to_lab, hsv_to_rgb, rgb_to_hsv
from einops import repeat
# from model.hed import hed_to_rgb, rgb_to_hed


In [ ]:
# Figure setup.
fig = plt.figure(figsize=(14, 12))
gs = GridSpec(2, 2, width_ratios=[4, 1], height_ratios=[1, 4])
ax1 = fig.add_subplot(gs[0])
ax3 = fig.add_subplot(gs[2])
ax3.axis('equal')
ax4 = fig.add_subplot(gs[3])
bins = 100
# Figure setup.

# Central scatter plot.
ax3.scatter(data[:,0],data[:,1], s = .5, alpha = .5)
sns.kdeplot(data[:,0], data[:,1],n_levels=10, cmap="viridis_r", ax = ax3, bw = 1)
ax3.scatter(np.mean(data[:,0]),np.mean(data[:,1]), marker = "o", color = "magenta")
ax3.scatter(max(set(first[:,0]), key=list(first[:,0]).count), max(set(first[:,1]), key=list(first[:,1]).count), marker = "*", c = "k")
ax3.scatter(max(set(second[:,0]), key=list(second[:,0]).count), max(set(second[:,1]), key=list(second[:,1]).count), marker = "*", c = "k")
# Central scatter plot.

# X distribution.
sns.distplot(data[:,0], ax = ax1, bins = bins)
ax1.scatter(np.median(data[:,0]),0, label = "median", marker = "s", c = "r")
ax1.scatter(np.mean(data[:,0]), 0, label = "mean", marker = "o", c = "magenta")
ax1.scatter(max(set(first[:,0]), key=list(first[:,0]).count),0, label = "modes", marker = "*", c = "k")
ax1.scatter(max(set(second[:,0]), key=list(second[:,0]).count),0, label="_nolegend_", marker = "*", c = "k")
ax1.legend()
# X distribution.

# Y distribution.
sns.distplot(data[:,1], ax = ax4, vertical = True, bins = bins)
ax4.scatter(0,max(set(first[:,1]), key=list(first[:,1]).count), marker = "*", c = "k")
ax4.scatter(0,max(set(second[:,1]), key=list(second[:,1]).count), marker = "*", c = "k")
ax4.scatter(0, np.mean(data[:,1]), marker = "o", c = "magenta")
ax4.scatter(0,np.median(data[:,1]), marker = "s", c = "r");
# Y distribution.

In [3]:
train_transform = transforms.Compose(
    [
        transforms.Resize(224),
        transforms.RandomHorizontalFlip(),
        transforms.RandomVerticalFlip(),
        transforms.ToTensor(),
        # transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225)),
    ]
)

test_transform = transforms.Compose(
    [
        transforms.Resize(224),
        transforms.ToTensor(),
        # transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225)),
    ]
)

In [5]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# trainset = HistoDataset(
#     root='/root/autodl-tmp/RandStainNA-master/classification/100K-NONORM-png/train0',
#     transform=train_transform,
# )
# train_loader = DataLoader(
#             dataset=trainset,
#             batch_size=1,
#             shuffle=True,
#             num_workers=15,
#         )        
testset = HistoDataset(
    root='/root/autodl-tmp/clas_experiments/tem5/tem5_9',
    transform=test_transform,
)

test_loader = DataLoader(
            dataset=testset,
            batch_size=1,
            shuffle=True,
#             num_workers=15,
        )      

for img, label in tqdm(test_loader):
    x = rgb_to_lab(img).to(device)
    mu = x.mean(axis=(2, 3)).to(device)
    sigma = x.std(axis=(2, 3)).to(device)
    mu0 = mu.mean(axis=0).to(device)
    sigma0 = sigma.mean(axis=0).to(device)
    print(mu0)
    print(sigma0)
    x = rgb_to_hsv(img).to(device)
    mu = x.mean(axis=(2, 3)).to(device)
    sigma = x.std(axis=(2, 3)).to(device)
    mu0 = mu.mean(axis=0).to(device)
    sigma0 = sigma.mean(axis=0).to(device)
    print(mu0)
    print(sigma0)
    
test_loader = DataLoader(
            dataset=testset,
            batch_size=5,
            shuffle=True,
#             num_workers=15,
        )      

for img, label in tqdm(test_loader):
    x = rgb_to_lab(img).to(device)
    mu = x.mean(axis=(2, 3)).to(device)
    sigma = x.std(axis=(2, 3)).to(device)
    mu0 = mu.mean(axis=0).to(device)
    sigma0 = sigma.mean(axis=0).to(device)
    print(mu0)
    print(sigma0)
    x = rgb_to_hsv(img).to(device)
    mu = x.mean(axis=(2, 3)).to(device)
    sigma = x.std(axis=(2, 3)).to(device)
    mu0 = mu.mean(axis=0).to(device)
    sigma0 = sigma.mean(axis=0).to(device)
    print(mu0)
    print(sigma0)
    


  0%|          | 0/5 [00:00<?, ?it/s]

tensor([ 73.6482,  19.4928, -13.0196])
tensor([17.2171, 12.5249,  9.1925])


 20%|██        | 1/5 [02:08<08:34, 128.57s/it]

tensor([4.9848, 0.2105, 0.8239])
tensor([1.0167, 0.1452, 0.1290])
tensor([41.2265, 48.1252, 12.8106])
tensor([12.7149,  9.6892,  8.9319])


 40%|████      | 2/5 [04:19<06:29, 129.83s/it]

tensor([5.9879, 0.6904, 0.6672])
tensor([0.5846, 0.1222, 0.1481])
tensor([68.1938, 23.5120, -7.0459])
tensor([12.3506,  7.3657,  4.6922])


 60%|██████    | 3/5 [06:30<04:20, 130.50s/it]

tensor([5.6407, 0.2607, 0.7955])
tensor([0.5089, 0.0973, 0.1086])
tensor([ 50.1595,  23.1264, -13.3275])
tensor([22.9706, 10.0159,  7.7661])


 80%|████████  | 4/5 [08:40<02:10, 130.46s/it]

tensor([5.2452, 0.3465, 0.5971])
tensor([0.7657, 0.1731, 0.2011])
tensor([ 62.4136,  31.1109, -17.6057])
tensor([13.6258,  9.3445,  6.1372])


100%|██████████| 5/5 [10:51<00:00, 130.33s/it]

tensor([5.2826, 0.3301, 0.7578])
tensor([0.5867, 0.1063, 0.1182])


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([59.1283, 29.0735, -7.6376])
tensor([15.7758,  9.7881,  7.3440])


100%|██████████| 1/1 [02:39<00:00, 159.01s/it]

tensor([5.4282, 0.3676, 0.7283])
tensor([0.6925, 0.1288, 0.1410])


In [6]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# trainset = HistoDataset(
#     root='/root/autodl-tmp/RandStainNA-master/classification/100K-NONORM-png/train0',
#     transform=train_transform,
# )
# train_loader = DataLoader(
#             dataset=trainset,
#             batch_size=1,
#             shuffle=True,
#             num_workers=15,
#         )        
testset = HistoDataset(
    root='/root/autodl-tmp/clas_experiments/tem5/tem5_10',
    transform=test_transform,
)

test_loader = DataLoader(
            dataset=testset,
            batch_size=1,
            shuffle=True,
#             num_workers=15,
        )      

for img, label in tqdm(test_loader):
    x = rgb_to_lab(img).to(device)
    mu = x.mean(axis=(2, 3)).to(device)
    sigma = x.std(axis=(2, 3)).to(device)
    mu0 = mu.mean(axis=0).to(device)
    sigma0 = sigma.mean(axis=0).to(device)
    print(mu0)
    print(sigma0)
    x = rgb_to_hsv(img).to(device)
    mu = x.mean(axis=(2, 3)).to(device)
    sigma = x.std(axis=(2, 3)).to(device)
    mu0 = mu.mean(axis=0).to(device)
    sigma0 = sigma.mean(axis=0).to(device)
    print(mu0)
    print(sigma0)
    
test_loader = DataLoader(
            dataset=testset,
            batch_size=5,
            shuffle=True,
#             num_workers=15,
        )      

for img, label in tqdm(test_loader):
    x = rgb_to_lab(img).to(device)
    mu = x.mean(axis=(2, 3)).to(device)
    sigma = x.std(axis=(2, 3)).to(device)
    mu0 = mu.mean(axis=0).to(device)
    sigma0 = sigma.mean(axis=0).to(device)
    print(mu0)
    print(sigma0)
    x = rgb_to_hsv(img).to(device)
    mu = x.mean(axis=(2, 3)).to(device)
    sigma = x.std(axis=(2, 3)).to(device)
    mu0 = mu.mean(axis=0).to(device)
    sigma0 = sigma.mean(axis=0).to(device)
    print(mu0)
    print(sigma0)
    


  0%|          | 0/5 [00:00<?, ?it/s]

tensor([ 68.1618,  18.8190, -15.7948])


 20%|██        | 1/5 [02:11<08:47, 131.88s/it]

tensor([12.3986,  4.1922,  5.4855])
tensor([5.0612, 0.2166, 0.7723])
tensor([0.2953, 0.0824, 0.1096])
tensor([ 77.0568,  15.5358, -11.4600])
tensor([15.5582, 10.9654,  9.1604])


 40%|████      | 2/5 [04:21<06:32, 130.71s/it]

tensor([4.8243, 0.1717, 0.8451])
tensor([1.1921, 0.1271, 0.1122])
tensor([85.4315,  6.6547, -3.6012])
tensor([15.4758,  9.6628,  5.9288])


 60%|██████    | 3/5 [06:32<04:21, 130.80s/it]

tensor([2.8742, 0.0798, 0.8821])
tensor([2.5893, 0.1191, 0.1162])
tensor([ 76.8864,  17.3920, -10.5947])
tensor([13.9332,  8.6885,  6.7381])
tensor([5.1419, 0.1798, 0.8493])


 80%|████████  | 4/5 [08:42<02:10, 130.52s/it]

tensor([0.9074, 0.1007, 0.1138])
tensor([86.8613,  5.5046, -2.6466])
tensor([9.9796, 6.3520, 2.9410])


100%|██████████| 5/5 [10:54<00:00, 130.86s/it]

tensor([5.1106, 0.0599, 0.8891])
tensor([0.9129, 0.0779, 0.0753])



  0%|          | 0/1 [00:00<?, ?it/s]

tensor([78.8796, 12.7812, -8.8195])


100%|██████████| 1/1 [02:39<00:00, 159.31s/it]

tensor([13.4691,  7.9721,  6.0507])
tensor([4.6024, 0.1416, 0.8476])
tensor([1.1794, 0.1014, 0.1054])


100%|██████████| 1/1 [02:39<00:00, 159.90s/it]


In [7]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# trainset = HistoDataset(
#     root='/root/autodl-tmp/RandStainNA-master/classification/100K-NONORM-png/train0',
#     transform=train_transform,
# )
# train_loader = DataLoader(
#             dataset=trainset,
#             batch_size=1,
#             shuffle=True,
#             num_workers=15,
#         )        
testset = HistoDataset(
    root='/root/autodl-tmp/clas_experiments/tem5/tem5_11',
    transform=test_transform,
)

test_loader = DataLoader(
            dataset=testset,
            batch_size=1,
            shuffle=True,
#             num_workers=15,
        )      

for img, label in tqdm(test_loader):
    x = rgb_to_lab(img).to(device)
    mu = x.mean(axis=(2, 3)).to(device)
    sigma = x.std(axis=(2, 3)).to(device)
    mu0 = mu.mean(axis=0).to(device)
    sigma0 = sigma.mean(axis=0).to(device)
    print(mu0)
    print(sigma0)
    x = rgb_to_hsv(img).to(device)
    mu = x.mean(axis=(2, 3)).to(device)
    sigma = x.std(axis=(2, 3)).to(device)
    mu0 = mu.mean(axis=0).to(device)
    sigma0 = sigma.mean(axis=0).to(device)
    print(mu0)
    print(sigma0)
    
test_loader = DataLoader(
            dataset=testset,
            batch_size=5,
            shuffle=True,
#             num_workers=15,
        )      

for img, label in tqdm(test_loader):
    x = rgb_to_lab(img).to(device)
    mu = x.mean(axis=(2, 3)).to(device)
    sigma = x.std(axis=(2, 3)).to(device)
    mu0 = mu.mean(axis=0).to(device)
    sigma0 = sigma.mean(axis=0).to(device)
    print(mu0)
    print(sigma0)
    x = rgb_to_hsv(img).to(device)
    mu = x.mean(axis=(2, 3)).to(device)
    sigma = x.std(axis=(2, 3)).to(device)
    mu0 = mu.mean(axis=0).to(device)
    sigma0 = sigma.mean(axis=0).to(device)
    print(mu0)
    print(sigma0)
    


  0%|          | 0/5 [00:00<?, ?it/s]

tensor([ 71.5421,  18.8019, -16.1848])
tensor([12.5121,  7.0799,  7.7980])


 20%|██        | 1/5 [02:10<08:40, 130.19s/it]

tensor([4.9755, 0.2119, 0.8121])
tensor([0.6219, 0.0939, 0.0948])
tensor([ 69.7712,  21.8404, -15.7030])
tensor([15.7183, 11.1385,  8.9338])


 40%|████      | 2/5 [04:23<06:36, 132.31s/it]

tensor([5.0409, 0.2356, 0.7949])
tensor([0.8042, 0.1283, 0.1157])
tensor([ 74.2486,  18.8146, -12.9439])
tensor([16.5039, 12.1015,  9.0588])


 60%|██████    | 3/5 [06:38<04:26, 133.36s/it]

tensor([5.0032, 0.2039, 0.8290])
tensor([0.9342, 0.1408, 0.1229])
tensor([79.1478, 15.3244, -8.5148])
tensor([19.5926, 17.2294,  9.5656])
tensor([4.7708, 0.1662, 0.8548])

 80%|████████  | 4/5 [08:46<02:11, 131.08s/it]


tensor([1.4641, 0.1865, 0.1299])
tensor([69.3211, 24.7903, -6.0176])
tensor([4.9580, 3.3053, 2.4178])


100%|██████████| 5/5 [10:55<00:00, 130.30s/it]

tensor([5.7576, 0.2648, 0.8181])
tensor([0.1295, 0.0397, 0.0482])


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 72.8062,  19.9143, -11.8728])
tensor([13.8570, 10.1709,  7.5548])


100%|██████████| 1/1 [02:36<00:00, 156.41s/it]

tensor([5.1096, 0.2165, 0.8218])
tensor([0.7908, 0.1178, 0.1023])


100%|██████████| 1/1 [02:37<00:00, 157.10s/it]


In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# trainset = HistoDataset(
#     root='/root/autodl-tmp/RandStainNA-master/classification/100K-NONORM-png/train0',
#     transform=train_transform,
# )
# train_loader = DataLoader(
#             dataset=trainset,
#             batch_size=1,
#             shuffle=True,
#             num_workers=15,
#         )        
testset = HistoDataset(
    root='/root/autodl-tmp/clas_experiments/tem5/tem5_12',
    transform=test_transform,
)

test_loader = DataLoader(
            dataset=testset,
            batch_size=1,
            shuffle=True,
#             num_workers=15,
        )      

for img, label in tqdm(test_loader):
    x = rgb_to_lab(img).to(device)
    mu = x.mean(axis=(2, 3)).to(device)
    sigma = x.std(axis=(2, 3)).to(device)
    mu0 = mu.mean(axis=0).to(device)
    sigma0 = sigma.mean(axis=0).to(device)
    print(mu0)
    print(sigma0)
    x = rgb_to_hsv(img).to(device)
    mu = x.mean(axis=(2, 3)).to(device)
    sigma = x.std(axis=(2, 3)).to(device)
    mu0 = mu.mean(axis=0).to(device)
    sigma0 = sigma.mean(axis=0).to(device)
    print(mu0)
    print(sigma0)
    
test_loader = DataLoader(
            dataset=testset,
            batch_size=5,
            shuffle=True,
#             num_workers=15,
        )      

for img, label in tqdm(test_loader):
    x = rgb_to_lab(img).to(device)
    mu = x.mean(axis=(2, 3)).to(device)
    sigma = x.std(axis=(2, 3)).to(device)
    mu0 = mu.mean(axis=0).to(device)
    sigma0 = sigma.mean(axis=0).to(device)
    print(mu0)
    print(sigma0)
    x = rgb_to_hsv(img).to(device)
    mu = x.mean(axis=(2, 3)).to(device)
    sigma = x.std(axis=(2, 3)).to(device)
    mu0 = mu.mean(axis=0).to(device)
    sigma0 = sigma.mean(axis=0).to(device)
    print(mu0)
    print(sigma0)
    


  0%|          | 0/5 [00:00<?, ?it/s]

tensor([24.0784, 33.7001, -5.4814])
tensor([14.3766,  8.8859,  7.2024])


 20%|██        | 1/5 [02:18<09:15, 138.84s/it]

tensor([5.6729, 0.7077, 0.3943])
tensor([0.3187, 0.1086, 0.1849])
tensor([82.2964, 10.9365, -7.1426])


 40%|████      | 2/5 [04:49<07:17, 146.00s/it]

tensor([10.0520,  6.4955,  5.0879])
tensor([5.0081, 0.1128, 0.8735])
tensor([1.0534, 0.0639, 0.0880])
tensor([ 60.7725,  31.5060, -16.7488])
tensor([19.7038, 16.4598,  9.1243])


 60%|██████    | 3/5 [07:10<04:47, 143.71s/it]

tensor([5.2411, 0.3589, 0.7386])
tensor([0.8539, 0.1940, 0.1393])
tensor([ 65.0635,  38.3990, -15.4694])
tensor([9.2253, 7.0327, 4.4181])


 80%|████████  | 4/5 [09:40<02:25, 145.92s/it]

tensor([5.5505, 0.3817, 0.8325])
tensor([0.1939, 0.0794, 0.0919])
tensor([78.6546, 19.1315, -9.1878])
tensor([8.1112, 6.4148, 3.6890])


100%|██████████| 5/5 [11:59<00:00, 143.99s/it]


tensor([5.4380, 0.1833, 0.8765])
tensor([0.4790, 0.0650, 0.0680])


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 62.1731,  26.7346, -10.8060])
tensor([12.2938,  9.0578,  5.9043])


100%|██████████| 1/1 [03:08<00:00, 188.50s/it]

tensor([5.3821, 0.3489, 0.7431])
tensor([0.5798, 0.1022, 0.1144])


100%|██████████| 1/1 [03:08<00:00, 188.90s/it]
